### PR TITLE
Various updates by antonmcclure and prologic

### PR DESCRIPTION
**Pull request by AntonMcClure**
This pull request merges changes present in both Kim Holviala's and Prologic's gophernicus repos to a single repo.

### CODE REVIEW

**Comment by AntonMcClure** [comment]
Edit to title: auto correct changed prologic to prologue

**Comment by AntonMcClure** [comment]
> Edit to title: auto correct changed prologic to prologue

Changed title to better reflect reason for this pull request.

**Comment by AntonMcClure** [comment]
updated title due to new commits

**Comment by fosslinux** [comment]
In addition, I don't really see the point of the examples directory. I'm going to nuke that directory, and as there's nothing in this PR that's needed, I'll close it.

Also, can you please next time split up your PR's? prologic's commits and yours are unrelated, so in future could you please split up your PR's into logical components?

Thanks :D

**Pull request closed without merging**
