### PR TITLE
Prevent possible leak of executable gophermap contents.

### PR DESCRIPTION
**Pull request by vext01**
Whilst reading the sources of gophernicus, I've found a security problem.

```
	/* Try to execute or open the mapfile */
#ifdef HAVE_POPEN
	if (exe) {
		setenv_cgi(st, mapfile);
		if ((fp = popen(command, "r")) == NULL) return OK;
	}
	else
#endif
		if ((fp = fopen(mapfile, "r")) == NULL) return OK;

	/* Read lines one by one */
	while (fgets(line, sizeof(line) - 1, fp)) {
```

If the system doesn't have `popen(3)`, then the contents of executable maps can be leaked to the client.

For example if I have a gophermap:
```
!test

run my script
=./script.sh
```

And an executable shell script in the same dir:
```
#!/bin/sh

/path/to/some/program --password topsecret
```

And I pretend my system doesn't have `popen(3)`:
```
diff --git a/menu.c b/menu.c
index 11004d3..3d9ef76 100644
--- a/menu.c
+++ b/menu.c
@@ -296,7 +296,7 @@ int gophermap(state *st, char *mapfile, int depth)
        }
 
        /* Try to execute or open the mapfile */
-#ifdef HAVE_POPEN
+#if 0
        if (exe) {
                setenv_cgi(st, mapfile);
                if ((fp = popen(mapfile , "r")) == NULL) return OK;
```

If we hit the gophermap:
```
$ ./in.gophernicus                              
/
itest   TITLE   null.host       1
i               null.host       1
irun my script          null.host       1
i               null.host       1
i/path/to/some/program --password topsecret             null.host       1
i______________________________________________________________________         null.host       1
i                     Gophered by Gophernicus/1.6 on OpenBSD/amd64 6.4          null.host       1
.
```

Oops! I've proposed a fix.

P.S.

I'm working on `pledge(2)` and `unveil(2)` support for gophernicus.

Can you tell me what shared memory is used for in gophernicus? It's not totally clear from the source (and for a relative nooby to gopher).

Cheers

### CODE REVIEW

**Comment by hb9kns** [comment]
Looks quite ok to me. But I've just begun trying to help out with maintaining gophernicus, so please remain patient!

**Comment by vext01** [comment]
I've fixed the indent and synced with master. If you agree with this change, I would like to squash and rebase the commits.

**Comment by vext01** [comment]
> might this break something by returning OK when popen dosen't exist?

I just copied what would happen if popen() should fail.

**Comment by hb9kns** [comment]
> > might this break something by returning OK when popen dosen't exist?
> I just copied what would happen if popen() should fail.

Agreed! I tested locally just to be sure: only thing that happens is that nothing is output instead of the stdout from the otherwise called popen, and I don't see any possible other effect.
So I think just returning ok is fine.

**Pull request merged**
